const STOPWORDS = ["0","1","2","3","4","5","6","7","8","9","_","a","actualmente","acuerdo","adelante","ademas","además","adrede","afirmó","agregó","ahi","ahora","ahí","al","algo","alguna","algunas","alguno","algunos","algún","alli","allí","alrededor","ambos","ampleamos","antano","antaño","ante","anterior","antes","apenas","aproximadamente","aquel","aquella","aquellas","aquello","aquellos","aqui","aquél","aquélla","aquéllas","aquéllos","aquí","arriba","arribaabajo","aseguró","asi","así","atras","aun","aunque","ayer","añadió","aún","b","bajo","bastante","bien","breve","buen","buena","buenas","bueno","buenos","c","cada","casi","cerca","cierta","ciertas","cierto","ciertos","cinco","claro","comentó","como","con","conmigo","conocer","conseguimos","conseguir","considera","consideró","consigo","consigue","consiguen","consigues","contigo","contra","cosas","creo","cual","cuales","cualquier","cuando","cuanta","cuantas","cuanto","cuantos","cuatro","cuenta","cuál","cuáles","cuándo","cuánta","cuántas","cuánto","cuántos","cómo","d","da","dado","dan","dar","de","debajo","debe","deben","debido","decir","dejó","del","delante","demasiado","demás","dentro","deprisa","desde","despacio","despues","después","detras","detrás","dia","dias","dice","dicen","dicho","dieron","diferente","diferentes","dijeron","dijo","dio","donde","dos","durante","día","días","dónde","e","ejemplo","el","ella","ellas","ello","ellos","embargo","empleais","emplean","emplear","empleas","empleo","en","encima","encuentra","enfrente","enseguida","entonces","entre","era","erais","eramos","eran","eras","eres","es","esa","esas","ese","eso","esos","esta","estaba","estabais","estaban","estabas","estad","estada","estadas","estado","estados","estais","estamos","estan","estando","estar","estaremos","estará","estarán","estarás","estaré","estaréis","estaría","estaríais","estaríamos","estarían","estarías","estas","este","estemos","esto","estos","estoy","estuve","estuviera","estuvierais","estuvieran","estuvieras","estuvieron","estuviese","estuvieseis","estuviesen","estuvieses","estuvimos","estuviste","estuvisteis","estuviéramos","estuviésemos","estuvo","está","estábamos","estáis","están","estás","esté","estéis","estén","estés","ex","excepto","existe","existen","explicó","expresó","f","fin","final","fue","fuera","fuerais","fueran","fueras","fueron","fuese","fueseis","fuesen","fueses","fui","fuimos","fuiste","fuisteis","fuéramos","fuésemos","g","general","gran","grandes","gueno","h","ha","haber","habia","habida","habidas","habido","habidos","habiendo","habla","hablan","habremos","habrá","habrán","habrás","habré","habréis","habría","habríais","habríamos","habrían","habrías","habéis","había","habíais","habíamos","habían","habías","hace","haceis","hacemos","hacen","hacer","hacerlo","haces","hacia","haciendo","hago","han","has","hasta","hay","haya","hayamos","hayan","hayas","hayáis","he","hecho","hemos","hicieron","hizo","horas","hoy","hube","hubiera","hubierais","hubieran","hubieras","hubieron","hubiese","hubieseis","hubiesen","hubieses","hubimos","hubiste","hubisteis","hubiéramos","hubiésemos","hubo","i","igual","incluso","indicó","informo","informó","intenta","intentais","intentamos","intentan","intentar","intentas","intento","ir","j","junto","k","l","la","lado","largo","las","le","lejos","les","llegó","lleva","llevar","lo","los","luego","lugar","m","mal","manera","manifestó","mas","mayor","me","mediante","medio","mejor","mencionó","menos","menudo","mi","mia","mias","mientras","mio","mios","mis","misma","mismas","mismo","mismos","modo","momento","mucha","muchas","mucho","muchos","muy","más","mí","mía","mías","mío","míos","n","nada","nadie","ni","ninguna","ningunas","ninguno","ningunos","ningún","no","nos","nosotras","nosotros","nuestra","nuestras","nuestro","nuestros","nueva","nuevas","nuevo","nuevos","nunca","o","ocho","os","otra","otras","otro","otros","p","pais","para","parece","parte","partir","pasada","pasado","paìs","peor","pero","pesar","poca","pocas","poco","pocos","podeis","podemos","poder","podria","podriais","podriamos","podrian","podrias","podrá","podrán","podría","podrían","poner","por","por qué","porque","posible","primer","primera","primero","primeros","principalmente","pronto","propia","propias","propio","propios","proximo","próximo","próximos","pudo","pueda","puede","pueden","puedo","pues","q","qeu","que","quedó","queremos","quien","quienes","quiere","quiza","quizas","quizá","quizás","quién","quiénes","qué","r","raras","realizado","realizar","realizó","repente","respecto","s","sabe","sabeis","sabemos","saben","saber","sabes","sal","salvo","se","sea","seamos","sean","seas","segun","segunda","segundo","según","seis","ser","sera","seremos","será","serán","serás","seré","seréis","sería","seríais","seríamos","serían","serías","seáis","señaló","si","sido","siempre","siendo","siete","sigue","siguiente","sin","sino","sobre","sois","sola","solamente","solas","solo","solos","somos","son","soy","soyos","su","supuesto","sus","suya","suyas","suyo","suyos","sé","sí","sólo","t","tal","tambien","también","tampoco","tan","tanto","tarde","te","temprano","tendremos","tendrá","tendrán","tendrás","tendré","tendréis","tendría","tendríais","tendríamos","tendrían","tendrías","tened","teneis","tenemos","tener","tenga","tengamos","tengan","tengas","tengo","tengáis","tenida","tenidas","tenido","tenidos","teniendo","tenéis","tenía","teníais","teníamos","tenían","tenías","tercera","ti","tiempo","tiene","tienen","tienes","toda","todas","todavia","todavía","todo","todos","total","trabaja","trabajais","trabajamos","trabajan","trabajar","trabajas","trabajo","tras","trata","través","tres","tu","tus","tuve","tuviera","tuvierais","tuvieran","tuvieras","tuvieron","tuviese","tuvieseis","tuviesen","tuvieses","tuvimos","tuviste","tuvisteis","tuviéramos","tuviésemos","tuvo","tuya","tuyas","tuyo","tuyos","tú","u","ultimo","un","una","unas","uno","unos","usa","usais","usamos","usan","usar","usas","uso","usted","ustedes","v","va","vais","valor","vamos","van","varias","varios","vaya","veces","ver","verdad","verdadera","verdadero","vez","vosotras","vosotros","voy","vuestra","vuestras","vuestro","vuestros","w","x","y","ya","yo","z","él","éramos","ésa","ésas","ése","ésos","ésta","éstas","éste","éstos","última","últimas","último","últimos"]


const FRASES = [
"me pregunto que hace tu numero de tlf en la puerta del bano de la uni",
"no tienes nada q responder josemi te ha dejado por los suelos",
"comprenderas que ante tal original contestacion nunca antes oida no pueda alegar nada",
"estas expulsado de conde",
"que se que te la suda",
"pero yo prefiero no tener gente tan deleznable y ruin en mi clan cuando yo lo necesito",
"te desearia que te vaya bien pero tus actos te condenan a que no sea asi ",
"con el tiempo mejor solo q contigo",
"no es un juego en auge",
"te echo como en su dia eche a vibe o a arecher",
"como toda la basura que ha pasado por el clan hay que sacarla",
"arrieros somos y en el camino nos encontraremos",
"te vas a cagar acuerdate",
"han pasado 20mil inutiles por aqui en muchos anos",
"y todos han acabado comiendome la polla",
"tu no te mereces ni eso pq te daria placer con lo salido q vas",
"ala pedazo de hijodeputa ahora juegas con tu puta madre",
"anda, relajate, tomate una tilita... y descansa un poco los dedos, te va a dar tendinitis",
"hasta en tu capacidad pauperrima de insultar vemos lo deficiente que eres",
"quien va a jugar contigo retrasado",
"con lo sabandija que eres copiando el texto",
"es que tu solo haces el pena sin que nadie te retrate",
"bueno, oficialmente ya no soy del clan conde",
"cuando ves a los frikis y repudiados del ano",
"quien coopera para regarlarle un libro a donyo para que amplie vocabulario",
"cayate q te vas a quedar solo",
"y de paso, para que no cometa falta de ortografia",
"cayate no, es callate",
"mira quien aparecio el otro friki",
"josemi: oid, si en el tzar peto a raza, estoy cometiendo un genocidio",
"donyo eres un comemierda y un abrazafarolas y un chupacharlos",
"tu aqui a seguir de bufon en el canal de un juego obsoleto",
"que a todos se os caen los huevos",
"ademas me cago en las mil pollas que se follaron a tu madre para embarazarla de ti",
"por que me gano la vida a base de mi fisico",
"si, porque con la cabeza ibas a pasar mas hambre que el perro de un ciego",
"inutil, que eres un inutil",
"te callas porque no sabes que decir mono de mierda",
"es q tu solo haces el pena sin que nadie te retrate",
"te gustaria tener la vida del mono eh",
"comecuandohay muerdealmoadas soplanucas",
"calla cono que me aburres ",
"ves, ya estoy aburrido",
"hasta en tu capacidad pauperrima de insultar vemos lo deficiente que eres",
"esa frase ya me las has dicho",
"vas a tener que leer mas",
"la repito por si no te enteras retrasado",
"y los letreros de salida de los bares no cuentan",
"aqui estais los putos frikis",
"inutil",
"inadaptados hasta para un juego en el q no teneis q mostrar la cara",
"joder que repetitivo eres",
"quedate ahi pudriendote",
"mientras yo viajo, veo sitios, me follo a diosas y gano mucho dinero",
"llevas tan buena vida que te pasas el dia enganchado haciendo el mono",
"claro claro si si como no seguro seguro fantasmon",
"a tomar por el culo ya me aburri",
"juega 5mil partidas mas a ver si llegas a mi nivel",
"un retrasado lo coge antes q tu",
"pues yo te lo pongo facil, lee un libro, sin dibujitos ni nada, y quiza hable contigo",
"ale, adios comecuandohay",
"putos frikis quedaos aqui",
"sois unos payasos",
"o unos mariconazos",
"y no teneis nada que hacer",
"nunca ganareis tanto como yo",
"k cono te has tomao donyo",
"me ha cabreadoel mont ese",
"ya te has pinchao los anabolizantes xd",
"me he pinchao a tu madre",
"ee tranki xd",
"sois todos unos payasos",
"dentro de un juego obsoleto al q no juega nadie",
"solo vosotros los frikis",
"y lo dices tu k llevas mas de 10 anos jugando a este juego",
"pero yo viajo veo sitios me follo a diosas y gano mucho dinero",
"q se os caen los huevos a todos",
"vas de nuevo ares jaja",
"dime de k presumes y te dire de k careces",
"no te sabes tu eso",
"tu si q vas de nuevo",
"no tienes ni idea",
"no tengo ni idea de bailar desnudo",
"no vayas de listo donyo xk no lo eres",
"de q sois todos unos frikis",
"quien te tuviera delante",
"ibas a llorar solo de verme",
"de verte la cara iba a llorar",
"no ves q en 10 dias me vuelvo a ny a ganar mas dinero del q ganars tu en mi vida",
"no vayas de flipao",
"a base de mi fisico",
"no hables de cara amor",
"entra en mi face",
"si y cuando no se te levante k vas a hacer",
"o cuando se te caigan esas tetitas",
"vivir debajo de un puente",
"ahi lo tienes campeon no te la pajees",
"uff lo intentare",
"enga campeon",
"pq si estuvieras aqui te tirabas por un puente con tal de nor ponerte delante mia",
"k se te de bien tu vida tan fantastica",
"me bas a comer la polla por debajo del culo",
"dame tu face ahora va q vamos a reirnos guapo",
"tienes q ser muy guapo y muy macho",
"siendo un mierdas como eres",
"sin vida de futuro",
"jajajjajajaajajajaj",
"el tipico violador miron",
"como una maruja el viernes noche con el salvame",
"como un maricon mirndo perfiles",
"y eso a k viene",
"a ti te falta un hervor",
"ya has cambiado de argumentes",
"viendo la escoria q eres al lado mio",
"esos porros k fumas deben ser mierda de moro",
"y lo sabes",
"xk te han dejao tonto",
"lo bueno es q te crees graciooso",
"cada vez q entras te humillan",
"yo voy a tener una carrera en 1 ano",
"y das pena por las partidas",
"cuando llegues tu a eso me avisas campeon",
"te repites mas k un disco rayao",
"por q eres retrasado y no te enteras",
"q sois todos unos frikis",
"me dices lo mismo k a mont",
"pidiendome consejos comiendome la polla",
"puto cerebro de moskito k tienes colega",
"y encima seguro k con los pinchotazos en el culo k te has pegao ni se te levanta",
"jajaja",
"voy a cenar ahora si kieres seguimos campeon",
"vamos juanjo puto internet",
"gane putos noobs",
"cuelga stats en la web q hizo un retrasado",
"pff q payaso",
"podras ganarme en comida oro y lo que sea pero en edificios destruidos no me ganas",
"por eso eres un noob",
"hace 2 dias comiendome la polla pidiendome consejos",
"con lo sabandija que eres",
"que soy el q viene aqui cuando no tiene nada q hacer debido a las condiciones de vida tan comodas de las que gozo",
"q le pasa a es te",
"has visto su cara de despojo",
"eso denota en tu personalidad un gran vacio",
"viajo",
"veo sitios",
"me follo a diosas",
"y gano mucho dinero",
"q a todos se os caen los huevos",
"bueno lo dicho que se de bien la noche",
"pero descuida entre hoy o manana lo vere",
"java no, c+ es un subconjunto de c",
"donyooooooo",
"feliz ano joder", 
"cuando ves a los frikis y repudiados del ano",
"eres espanol. se muy bien que en argentina existe una terrible discriminacion hacia la gente como tu. por eso no me sorprende tu comentario. demuestras un claro resentimiento hacia ellos. no te culpo, a mi me parece muy feo que alguien se burle de la gente de un pais por tener una complexion fisica caracteristica de los indios americanos o porque el pais sea de los mas subdesarrollados del continente.",
"recibiste los platanos de regalo de navidad",
"la cruda realidad es que no tienes para regalos",
"y que te levantaras esperando recibir cualquier mierda",
"me deje la pasta en los platanos",
"pq eres un pelele",
"q a todos se os caen los huevos",
"calla raza joder",
"callate razaga",
"le envio un mail a arek para que te banee",
"me cago en vuestras hostias joder",
"recibiste los platanos",
"me los estoy metiendo por el culo",
"no hay nada que seguir tontito",
"me voy a entrenar",
"a follar diosas",
"tu a seguir aqui de bufon de un canal de un juego obsoleto",
"te sueltan de la jaula",
"tu vida promete",
"para entrenar eh",
"eso denota en tu personalidad un gran vacio",
"ajaja lol",
"con lo sabandija que eres",
"q a todos se os caen los huevos",
"nos liamos a navajazos o que",
"lo gracioso es que use mis textos",
"me haces sentir importante",
"aunque bueno en tu mierda de vida esto debe ser algo importante",
"el mono del circo mas famoso del mundo",
"hablar con un mono que baila",
"sisi",
"pagarias por tener la vida del mono eh",
"yo sin embargo viajo veo sitios me follo a diosas y gano mucho dinero",
"amen hermano",
"y gano mucho dinero",
"dilo bien alto que el mito no morira nunca",
"ely que las prostitutas, asi que si ves una puta en la prostitucion, la prostitucion de pollo, no lo hemos hecho, que cono esta en riesgo debido a nuestra reputacion.",
"ahora donde estas en el circo o en el zoo",
"te mande los platanos al zoo",
"me quede uno para tu madre",
"en serio tio no llegas al minimo eh",
"estoy con fatal q se ha ido de tu partida",
"hasta en tu capacidad pauperrima de insultar vemos lo deficiente que eres",
"te ha dejado colgado como una puta mierda",
"es que tu solo haces el pena sin que nadie te retrate",
"espero que el 2015 te depare lo que tu te ganas",
"y estoy seguro de que asi  lo hara",
"un buen camion de platanitos",
"pq no le damos una propina a la cacho puta de tu madre",
"me gusta la gente que no se llama frank",
"asi son siempre cuando estan estos dos xdd",
"es un descojone xd",
"siempre se pican",
"no te equivoques raza",
"no me deja hablar",
"esta todo el rato",
"aqui estais los putos frikis",
"vibe se ha ido",
"como vosotros",
"inadaptados hasta para un juego",
"no para de hablar de su zoo",
"en el que no teneis ni q mostrar la cara",
"y luego esstoy yo",
"ostia si",
"vete a la puta mierda",
"eres un mono del zoo",
"puto cabron cabronazo",
"raza hijo de mil negros mal nacido",
"deja al pobre igual lo violan en el circo",
"me cago en tu madre de mierda, veste a cagar hormigones",
"que soy el q viene aqui cuando no tiene nada q hacer debido a las condiciones de vida tan comodas de las que gozo",
"has visto su cara de despojo",
"a la cafeteria esa de mierda",
"y encima vengo y os apalizo",
"mejor q las mias no",
"viajo",
"veo sitios",
"me follo a diosas",
"esa se quedad apuntada xd",
"y gano mucho dinero",
"calla joder q no tienes criterio",
"dejame hablar a mi me entiendo con animales",
"que se de bien la noche palurdos",
"donyo espera",
"como son las entradas del zoo",
"tu eres un gorila que baila y eso no lo cambiara nadie",
"raza estas con tsu en mine",
"noooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"xdddddddddddddd",
"pobre ya lo sacaron de la jaula",
"estara con las coreografias y tal",
"hola alguna partida que qiera perder alguien",
"mas bien que quiera petar",
"ja parece alguien perdio",
"eres un comewevos q baila",
"joder no puedo copiar",
"vamos los 3 vs 8 pcs",
"joder si los 3 sabemos jugar",
"eso no dura ni 20 min",
"con el unico que gane a las pc fue con scorki",
"pues nos ganaron a josemi a mi y a wolf las 5 maquinas",
"yo soy experto en eso",
"que guapo soy",
"si o queee",
"estoy levantandome a la hija del embajador de espana en colombia haber si me dan el pasaporte de una ves por todas",
"partidita macbook pro nuevo y ese payaso q se cambia el nombre",
"razgaa has comido",
"para parecer que tiene un apple mierdoso",
"and, nos liamos a navajazos o que",
"no os confundais, no soy racista. el racismo es un crimen y el crimen es cosa de negros",
"i may have raped a hiv positive woman, but i will be fine because i took a shower afterwards.",
"nobody speaks french. even the french don't. they just pretend to for the tourists.",
"scusa l'umorismo spicciolo xd e l'orario",
"me rei tanto, continuara en el area de la bahia y en la maquina, curva lineal, universidad de explotariamos y confirmo que en hollywood, planta de energia nuclear de michael bay",
"me he reido tanto, que si fuera ahora mismo en coche, y tomara una curva, no giraria, iria recto al precipicio y yo y el coche explotariamos cual central nuclear, aprobado por la universidad de hollywood, fundada por michael bay",
"he visto flanes de vainilla con mas huevos que tu.",
"eres colombiano. se muy bien que en argentina existe una terrible discriminacion hacia la gente como tu. por eso no me sorprende tu comentario. demuestras un claro resentimiento hacia ellos. no te culpo, a mi me parece muy feo que alguien se burle de la gente de un pais por tener una complexion fisica caracteristica de los indios americanos o porque el pais sea de los mas subdesarrollados del continente.",
"de una puta y un gitano nacio el primer murciano",
"i am the king of kings, the god of godss, the king of the 7 kindoms, the protector of the rome, the capo di tutti li cappi, the cosa nostra boos, the head of the king....... ",
"the god of the olimpo, the fuking king / god ares",
"tu un payaso q baila y eso no lo cambiara",
"eres un comewevos",
"para todos nosotros",
"asi q ale",
"tu a seguir con lo tuyo",
"no sabes en lo q trabajo",
"es mas honrado q lo tuyo",
"jajajajajaja honrado",
"no hay nada de deshonrado en lo mio",
"viajo",
"veo sitios",
"me follo a diosas",
"y gano mucho dinero",
"lo tuyo es honrado pues nice",
"quedate con tu honradez",
"haha",
"venga si",
"jajajajaja",
"sisi mira mi facebook",
"q te vas quedar solo",
"q a todos se os caen los huevos",
"noooooooo",
"solo te quedas tu",
"que la gente quiere jugar",
"y les j odes y pasan de ti",
"pasaran de ti",
"eso denota en tu personalidad un gran vacio",
"por q yo solo peto tus partidas",
"aburrimiento no tenia nada que hacer",
"no te equivoques",
"petas nuestras partidas",
"si a la gente le haces perder el tiempo",
"son tuyas por q tu mandas",
"sin tener culpa",
"es su tiempo no el mio",
"tonto rubennnn",
"el hama se peta poniendo link y flodeando",
"depende de tu ordenador",
"si es malo",
"petara el primero",
"nos peto a todos",
"pero poniendo texto na mas no se peta",
"un mensaje bueno por cada milisegundo o asi",
"cada vez que juegue donyo lo vas a hacer no",
"por lo tanto te odian a ti",
"su sabes lo que estaban diciendo",
"de ti y del otro en la partida",
"no te ovy a poner",
"hundele en la ruina",
"todos conmigos",
"y tu y el otro fracasados y solos",
"ese es vb",
"y se os dio la oportunidad",
"el otro es frank",
"ma questo con tu sposa",
"auxiliar de humillacion",
"tanta paz nos dejes como guerra nos das",
"sara perdon estaba despistado y cuando pediste pausa en lugar de dar pausa di suprimir y tenia mi granja seleccionada",
"frnak ya sabe insultar llamo payaso a alberto",
"yo le ensenare mis insultos",
"mis mensajes te sirven para avisarte de q tienes esto encendido",
"ya con eso lo cierras",
"imagine que es una zorra y una puta en taiwan alrededor de la casa, o una prostituta que pago a prostitutas para ser mejores y para otra de forma rapida. pero el proxeneta, que es un monton de dinero. cada perra en el mundo ",
"slut",
"desde los fideos de nuevo a la vida, solo, solamente, y estan cansados de putas, prostitutas, y ahora esta prostituta puta puta despues de el, pero el dice: de todo el rio estupido o maldita ",
"tenemos la libertad para construir su casa, quiere gravar a las prostitutas. damn obsesionado rapidamente con el dinero no hay mucho sol: el gancho es muy dificil para las prostitutas y otros trabajadores del sexo para entender, por ejemplo, usted es mujer, usted puede crear su propio idioma, como en el caso del frances, griego, rumano, lo que! usted estara de acuerdo en que un buen dominio de la prostitucion mas idiomas. prostitutas, prostitutas y luego la calle les doblan apenas una manera de dejar ir. ",
"otro problema son las malditas mujeres equivocadas en la misma habitacion, los corredores de beneficios y otra puta zorra que no sabe, pero sucede al frente y atras, perra, perra no lo hacen. ",
"los numeros almacenados en la maldita mano, en todas partes, el color de la perra y no hay manera de instalar un nuevo hogar para su puta sucia de mierda ...... ",
"esta perra que sienten que tienen que decidir que tipo de casa force prostitutas mea ... ",
"y que las prostitutas, asi que si ves una puta en la prostitucion, la prostitucion de pollo, no lo hemos hecho, que cono esta en riesgo debido a nuestra reputacion.",
"just have dragones with archers die...",
"ahora cuando tu hermana termine de chuparmela te respondo, no te preocupes",
"a lo vuestro, mosquitos",
"el estado de animo en el mismo procesador fisico, similar al ataque de los enemigos",
"donyo me han llamado del zoo",
"dicen q vayas a hacer una actuacion",
"quieren ver a un gorila bailar",
"estoy con fatal q se ha ido de tu partida",
"te ha dejado colgado como una puta mierda",
"lo recurdas saco de mierda",
"acabas de ponerte la cruz vas a enterarte",
"mi mujer me hizo altavoz",
"te acordaras de lo miserable q eres",
"te acordaras de lo miserable q eres, te lo hare recordar ;)",
"te lo hare recordar ;)",
"ya nos vemos por el circo",
"te han sacado de la jaula ya",
"hace dos dias comiendome la polla",
"hace dos dias comiendome la polla pidiendome consejos para mejorar",
"te lo repito",
"pidiendome consejos",
"no soy tu mano",
"para mejorar",
"de poco sirvieron",
"comiendome los huevos",
"comiendome los huevos como la sabndija q eres",
"como la sabndija q eres",
"si eso se ve eres malo hagas lo q hagas",
"juega anda",
"juega anda q lo necesitas",
"q lo necesitas",
"juega 5mil partidas mas",
"no llevo 10 anos",
"a ver si llegas al nivel",
"jugando al tzar como tu",
"ni sara ni wmls",
"y mira su nivel y el tuyo",
"xdddddddddd",
"q pasa con mi nivel",
"un retrasado lo coge antes q tu",
"soy peor q tu vale",
"no se en que modo crees que me pejudicaria desinstalarlo",
"cuando llevo mas de un ano sin jugar",
"pues venga, estas tardando",
"que josemi me da frases guapas",
"tu no mandas en mi, gilipollas",
"puto catalan separata",
"que fino eres, es verdad unbe, tienes razon",
"josemi, no te lo desistales",
"es una orden",
"asi que como deje de verte por aqui te parto el pecho",
"puto murciano",
"tu quieres que te parta el pecho o que puto murciano",
"vienes o has muerto por la calle",
"dale un platanito a tu madre ya de paso",
"tu eres subnormal",
"nehon pq no le damos una propina a la cacho puta de tu madre",
"aqui la unica que come platanos es tu puta madre",
"nehon es retrasado",
"hace dos dias comiendome la polla para jugar y ahora va de subido",
"es el mismo saco de mierda",
"menudo payaso",
"me gusta la gente que no se llama frank",
"todos los italianos hablan espanol",
"eeeeeeeeeeee",
"pirate de mi puto barrio o te lleno de plomo, pavo",
"lol xd",
"lol que, quieres dormir tu tb con los peces",
"sigo infundiendo miedo..",
"ajajajjajaja",
"qu pasa perro flauta",
"qu pasa perro flauta te doy 2 ostias y te undo",
"te doy 2 ostias",
"y te undo",
"yo por mi nos liabamos a ostias pero rapido",
"pero no me gustaria ver a tu madre de luto",
"esta gente...",
"me pasais el hamachi ese",
"dais mas asco que el que siente spr alberto por davio y xekbo",
"eso es mucho de dios eh",
"a quienes le dices",
"a wolf y razaga",
"pues es cierto lo dais",
"me canse ya",
"jode que te maten y que se ponga a bailar encima de tu cadaver llamandote noob",
"esto son un cruzado y un infante que estan charlando antes de la batalla. tio, creo que mi mujer me pone los cuernos. por que piensas eso dice el infante.  me ha dicho, haber si te mueres de una vez, que hay 20 como tu esperando en la casa del padre",
"esto es un campesino que esta explorando y se encuentra otro paseando lejos de su base. hey has encontrado minas. el otro campesino contesta sorprendido.  a mi no me mires yo estoy ordenando vacas.",
"esto es un sacerdote chino y un monje que estan meditando. oooooooooooooommmm, ooooooooooooommm. sin abrir los ojos el sacerdote dice. pequeno saltamontes, estas no te oigo un enano contesta. pequeno saltamontes tu padre. que el calvo de tu hijo hace una hora que se fue.",
"i preffer bigger one",
"even ares has crawled back under his rock",
"intente jugar y no pude. asin que paso de jugar a una version q no me gusta y que encima no quieran cambiar las normas de siempre",
"solo me importa el proyecto siempre que se pueda hacer",
"entre en la partida de sara y si las tenia. hasta el min 12 no vale atacar minas. no vale atacar casas y granjas y eso incluye a los campesinos. paso",
"lo gracioso es que comienzan con 1500 de todo. de verwensa.",
"en fin. haber cuando nos organizamos de nuevo para esto.",
"no me da tiempo de echar apenas una partida, pero si de leer el quijote referido a la 1.13b",
"que tu hai otra web",
"1.11 is a graveyard",
"where dinosaur donyo live",
"drex",
"eat shit nehhon xd",
"violaremos a vuestros caballos y huiremos en vuestras mujeres",
"nos comeremos a vuestros hijos mientras vuestras comidas miran",
"i am tired",
"i am tired of being a rusian bastard",
"of being a rusian bastard",
"lo hice el otro dia por hacer la gracia...",
"jjestem. ale nigdy nie lubilem 1,11",
"yo tampoco te considero persona",
"te considero vaca",
"no just common sense",
"common mis cojones",
"ooohh my goddd",
"ooohh my goddd such a big trouble 2 wizzard oohhh jesus crist",
"such a big trouble",
"2 wizzard",
"oohhh",
"jesus crist",
"te pego",
"venga maricas",
"digo venga razaga",
"i will give one thousabd euros to anyone who joins",
"for once i am glad to see mamut",
"hhhhhhhhhhh",
"pero no salgais puots payasos",
"ai k saber perder",
"kurwa",
"yo trato mejor a un perro que veo por la calle que a xekbo o davio",
"donovan, el hamachi es peligroso o te abre los poros o como se diga del pc porfavor di la verdad.",
"este juego es tan alucinante que cuando lo estaba viendo mi madre entro y penso que habia estado otra vez con las drogas, pero le dije que solo era un juego... lo malo es que mi madre murio hace 2 anos y yo ni siquiera tengo ordenador",
"osea que... sin vacilar ni deprimir aposta, no tienes ni madre ni ordenador y consigue jugar a tzar, y cuando jugabas tu madre te vio, osea, que quedamos que tu tienes un ordenador en la cabeza y tu madre es un fantasma, o esa es mi idea xdd.",
"._.",
"mi ip",
"sara joder consigue novio",
"fracasada fea",
"obeja",
"obeja obeja obeja obeja obeja obeja obeja",
"yo soy ares",
"el dios de los mares",
"el que reparte ostias a pares",
"el que destroza conos y putas por iguales",
"the king of kings",
"the fuking master",
"the god of goddes",
"the big ares",
"sara",
"sara estas expulsada de conde",
"estas expulsada de conde",
"que se que te la suda",
"pero yo prefiero no tener gente tan deleznable y ruin en mi clan cuando no lo necesito",
"te desearia que te vaya bien",
"pero tus actos te condenan a que no sea asi ",
"con el tiempo",
"con el tiempo mejor solo q contigo",
"mejor solo q contigo",
"no es un juego en auge",
"pero te echo",
"como en su dia eche a vibe o a arecher",
"como toda la basura que ha pasado por el clan",
"hay que sacarla",
"lo se ^^",
"arrieros somos",
"arrieros somos y en el camino nos encontraremos",
"y en el camino nos encontraremos",
"te vas a cagar",
"te vas a cagar acuerdate",
"acuerdate",
"han pasado 20mil inutiles por aqui",
"en muchos anos",
"y todos han acabado comiendome la polla",
"pero tu no te mereces ni eso",
"pq te daria placer con lo salida q vas",
"sombra",
"en fin, tsu se nos fue a estudiar, tendremos que tirar nosotros, hasta el retorno del lider, estreno en julio 2013, tomo las riendas como lider",
"en funciones, de drk, por que una vez tuve un sueno, un clan, que se impondria sobre spr, conde y otros... y ese sueno se hace realidad gracias a vosotros",
"prometo seguir elevando el nivel de calidad, y la popularidad tanto del clan, como de sus jugadores aplausos",
"hola soy nuevo ",
"darme la bienbenida",
"soy ares",
"soy espanol y os voy a rebentar a todos porque soy el mejor",
"polacos y demas pallasos os vais a cagar con el gran ares",
"hola",
"hola soy nuevo ",
"darme la bienbenida",
"soy ares",
"soy espanol y os voy a rebentar a todos porque soy el mejor",
"italianos y demas pallasos os vais a cagar con el gran ares",
"yo soy ares",
"el dios de los mares",
"el que reparte ostias a pares",
"el que destroza conos y putas por iguales",
"the king of kings",
"the fuking master",
"the god of goddes",
"the big ares",
"ares",
"ala pedazo de hijodeputa",
"ahora juegas con tu puta madre",
"que tal donyo como estas",
"juega con lancelot",
"estoy con fatal",
"q se ha ido de tu partida",
"y te ha dejado colgado",
"como una puta mierda",
"lo recurdas",
"saco de mierda",
"acabas de ponerte la cruz",
"i haven't chanse with him",
"haha donyo",
"estabamos jugando mapa",
"te has uqedado solo tu",
"otra",
"me hace gracia donyo",
"solo nehon",
"estoy con fatal dice",
"y estabamos jugando",
"uegas mapa",
"si ven",
"como un retrasado",
"quieres jugar conmigo",
"es tu opinion",
"1vs1 quizas",
"yo tnego opiniones",
"como q el hamachi abre poros",
"xddddddddddd",
"que dices",
"lo del pescado tsu como era",
"eh nehon",
"el aceite de pescado abre poros",
"algo asi era donyo",
"vas a enterarte",
"mi mujer me hizo altavoz",
"te acordaras de lo miserable q eres",
"te lo hare recordar ;)",
"ya nos vemos",
"por el circo",
"te han sacado de la jaula ya",
"hace dos dias comiendome la polla",
"te lo repito",
"pidiendome consejos",
"no soy tu mano",
"para mejorar",
"de poco sirvieron",
"comiendome los huevos",
"como la sabndija q eres",
"si eso se ve",
"eres malo",
"hagas lo q hagas",
"muy bien",
"juega anda",
"q lo necesitas",
"juega 5mil partidas mas",
"no llevo",
"10 anos",
"a ver si llegas al nivel",
"jugando al tzar como tu",
"ni sara",
"ni wmls",
"y mira su nivel",
"y el tuyo",
"xdddddddddd",
"q pasa con mi nivel",
"un retrasado lo coge antes q tu",
"soy peor q tu vale",
"q yo",
"tu quieres que te parta el pecho o que puto murciano",
"y que todos",
"menos los noobs",
"a ver",
"estamos hablando de mi",
"murciano",
"no de ti",
"yo siempre he dicho",
"que el estado de animo del procesador fisico",
"es similar",
"al ataque de los enemigos",
"no le import a nadue",
"lo que tu digas",
"pirate de mi puto barrio o te lleno de plomo, pavo",
"no lo ves",
"sigo infundiendo miedo..",
"yo por mi nos liabamos a ostias pero rapido",
"quien te tuviera delante",
"pero no me gustaria ver a tu madre de luto",
"ibas a llorar",
"solo de verme",
"con esa cara",
"nehon",
"ostia ahi te ha roto hermano",
"nehhon",
"no hables de cara amor",
"common mis cojones",
"no ves q en 10 dias",
"me vuelvo a ny",
"ny o basura",
" a ganar mas dinero del q ganaras tu en tu vida",
"a base de mi fisico",
"como hablas de fisico",
"en el vertedero",
"pequeno mojon",
"poco encontraras amigo",
"fisico de rata",
"sisi",
"di lo q quieras",
"entra en mi face",
"digo la verdad",
"va campeon",
"entra",
"pasate",
"pasa link",
"a ver lo q ves",
"fotos q no son tuyas",
"pasa",
"jorge ferreira despedidas",
"ahi lo tienes campeon",
"buscame",
"no te la pajees",
"que se que te pongo",
"madre mia",
"mas quisieras",
"me muero",
"sisi",
"muerete",
"pq si estuvieras aqui",
"te tirabas por un puente",
"con tal de no ponerte delante mia",
"y lo sabes",
"me tiro por el puente",
"antes de verte",
"y todos",
"logico",
"dame tu face ahora va",
"q vamos a reirnos",
"guapo",
"haha",
"no lo uso amiguete",
"ostia y que haces jugando al tzar con lo mayor que eres y con ese fisico",
"dda =",
"q no lo uses",
"ni tengo fotos",
"jajajaja",
"tienes q ser muy guapo",
"y muy macho",
"mas q una rata",
"para no tener ni fotos",
"jajajajajajajaajajajajaaja",
"a ver",
"no pierdo el tiempo",
"jajajajajajajajajajajajaja",
"en redes sociales",
"sin fotos",
"subiendo fotos",
"el tipico violador",
"miron",
"a ver",
"si no tienes fotos",
"quitatelo",
"no lo uso",
"si no lo usas",
"quitatelo",
"aaaah nooo",
"que asi puedes chafardear",
"a ver",
"como una maruja el viernes noche con el salvame",
"como un maricon",
"claro q si",
"mirando perfiles",
"donyo",
"que",
"no todos tenemos los mismos habitos que tu",
"ya has cambiado de argumentos",
"esperad que voy por palomitas",
"donyo",
"viendo la escoria q eres al lado mio",
"y lo sabes",
"venga si",
"y tanto q si",
"este juego es tan alucinante que cuando lo estaba viendo mi madre entro y penso que habia estado otra vez con las drogas, pero le dije que solo era un juego... lo malo es que mi madre murio hace 2 anos y yo ni siquiera tengo ordenador",
"lo bueno es q te crees gracioso",
"estamos aqui para jugar",
"cada vez que entras",
"te humillan",
"y das pena por las partidas",
"yo prefiero no tener gente tan deleznable y ruin en mi clan cuando no lo necesito",
"no hace falta q digas nada",
"tu situacion es tan lamentable que ya nos reimos bastante",
"te desearia que te vaya bien",
"pero tus actos te condenan a que no sea asi ",
"vaya par",
"jajaajjajaja",
"copiando mis palabras",
"arrieros somos",
"ahora siiiii",
"imitandome",
"y en el camino nos encontraremos",
"copiando lo q digo",
"te vas a cagar",
"han pasado 20mil inutiles por aqui",
"jajajajaja",
"lo q le dije a sara",
"en muchos anos",
"miralo",
"y todos han acabado comiendome la polla",
"copiandolo",
"hjajajajajajaja",
"pero tu no te mereces ni eso",
"pq te daria placer con lo salido q vas",
"1.11 is a graveyard",
"where dinosaur donyo live",
"jajajaja",
"donyo pq no le damos una propina a la cacho puta de tu madre",
"jajajaja",
"aqui la unica que come platanos es tu puta madre",
"con q dinero",
"menudo payaso",
"con el de tu mama",
"el q te tiene q dar tu mami",
"xdddddddddddd",
"te doy 2 ostias",
"y te undo",
"qu pasa perro silbato",
"dice",
"le damos una propina a tu madre",
"y se queda esperando q se rian",
"dais mas asco que el que siente spr alberto por davio y xekbo",
"cuando la realidad es q el muy subnormal no tiene un puto duro",
"para pagar algo tiene q pedirselo a la mama",
"no donyo",
"y esta metido en el pc",
"no todos hacemos lo mismo q tu",
"como una rata",
"no pone fotos en el face",
"imaginate su cara de trapo ",
"perdone usted",
"usado para limpiar retretes",
"es un pecado",
"no usar facebook",
"jajajajajaja",
"no te describas anda",
"no lo usas",
"pero lo tienes",
"violaremos a vuestros caballos y huiremos en vuestras mujeres",
"para queeeee'",
"yo tampoco te considero persona, te considero vaca",
"eso lo hace la gente envidiosa",
"donyo",
"lo cree una vez",
"y ahi lo tnego tirao",
"si te quedas mas tranquilo",
"no sera q tienes un poco de envidia",
"lo borro ahora",
"eso nos da una buena constancia de tu vida social",
"lo que te aprecia tu entorno",
"jajajajajaj",
"la gente que conoces",
"y como te muestras ante ellos",
"ocultando la foto",
"jajajajajaja",
"ocultando tu imagen de despojo ",
"xdddddddddddd",
"madre mia",
"no tienes q ser feo ni nada cabron",
"donyo ya paraas de hablar contigo mismo",
"nehon",
"quieres skype",
"quiero verte la cara de trapo q tienes",
"q tienes",
"nehon va tio",
"no te hagas el sueco",
"queremos ver tu preciosa tez",
"jugamos mapaaa",
"estamos en partida",
"os la peto",
"pues",
"no funciona",
"pero",
"no la he petado ya=",
"la has petado tu",
"va jugamos mapas",
"es espectacular q aun haya gnte aqui que siga tratando con el retrasado este",
"contigo",
"paso de jugar mapas",
"me voy ",
"alguien q peta partidas",
"y deshace el juego",
"ah solo algunas",
"deshacer el juego tu ya lo hiciste",
"ahi os quedais a jugar con el",
"asi es",
"tu vete a bailar",
"nehon eres la lacra q nadie quiere",
"no te das cuenta peqeno",
"pequeno",
"pero seguramente si estuvieramos juntos",
"acaso le hablas a tu pene",
"se te quitarian las tonterias",
"i may have raped a hiv positive woman, but i will be fine because i took a shower afterwards.",
"de una puta y un gitano nacio el primer murciano",
"q donyo",
"como vas",
"eres un comewevos",
"q baila",
"y eso no lo cambiara",
"asi q ale",
"tu a seguir con lo tuyo",
"pff, parad ya",
"has estado en ny",
"hola gentuzilla",
"pero he estado en badajoz",
"onani, en el peor momento entraste xd",
"y en caceres",
"cuando a tu madre trabajando de puta le llegue para coger un avion",
"pues tengo una dudilla sobre jugar al tzar",
"...",
"no tienes q ser feo ni nada cabron",
"pff",
"nos lo cuentas",
"eso lo hace la gente envidiosa",
"pues estos no te la resolveran",
"jajajaja",
"envidiosoooo",
"eso nos da una buena constancia de tu vida social",
"cuentanos nehon",
"basicamente, aunque ponga el hamachi, no hay dios que encuentre la partida de mi colega",
"follas mucho",
"a alguien le funciona el hamachi sin tener que liar la de dios",
"con tu madre si",
"jjaajajaja",
"fantaseando con mi madre",
"si con una ratilla",
"esta guapo caceres o q",
"estate quieto ahi ocultando tu imagen de despojo ",
"follaste mucho",
"muchismo",
"jajajajajaja",
"nos estamos cansando, despues de desconectarse de nuestra sala sin pactar nada con nosotros los azores y teniendo una sala que iba bien de ping, nos obligan ir a tres salas 2 de ellas que ni van nosotros aceptamos aunque no le vemos sentido si iba bien la sala para jugar ahora en una sala peor de ping, luego decir despues de 15 minutos que quieren volver a la nuestra. y luego es defwin para ellos... claro...",
"hace dos dias comiendome la polla",
"para jugar",
"y ahora va de subido",
"aqui la unica que come platanos es tu puta madre",
"sigue",
"retratate un poco mas",
"asi que como deje de verte por aqui te parto el pecho",
"tu no mandas en mi, gilipollas",
"puto catalan separata",
"que los nuevos aun tienen dudas de si eres subnormal profundo o entrenas la habilidad de hacer tonto y el pena",
"eso denota en tu personalidad un gran vacio",
"por q yo solo peto tus partidas",
"si a la gente le haces perder el tiempo",
"sin tener culpa",
"es su tiempo no el mio",
"nehon la gente te maldice",
"su sabes lo que estaban diciendo",
"piensa q eres retrasado",
"por lo tanto te odian a ti",
"de tu ordenador",
"por cada milisegundo",
"pero si sois la basura de aqui hoy por hoy",
"perro silbato",
"bueno pequeno friki pajillero",
"no te describas mas",
"ahi te dejo con tu inmundicia",
"ya te conocemos",
"jorge ferreira despedidas",
"si eso es cierto",
"auxiliar de humillacion",
"jajajajajajajajaaj",
"estate quieto ahi ocultando tu imagen de despojo ",
"donyo me han llamado del zoo",
"pero no ocultaba mi imagen",
"venga",
"dicen q vayas a hacer una actuacion",
"muestra la tuya ahora",
"quieren ver a un gorila bailar",
"q nos queremos reir",
"va figura",
"eso denota en tu personalidad un gran vacio",
"pon tu face aki",
"que queremos verte la cara de triunfador que tienes",
"vengaaaa pasa fotito",
"pobre loser",
"q vida de fracasado tienes",
"donyo cuando dejes hablar contigo",
"puedo hablar yo",
"dejad de petar el chat",
"amen hermano",
"quedate con tu honradez",
"gran sabio dijo esas palabras",
"y tu las copias y las guardas",
"se que me quieres",
"mi princesita!!!",
"hace dos dias comiendome la polla",
"pidiendome consejos",
"seguro que si nos ven por la calle a los 2",
"para mejorar",
"comiendome los huevos",
"discrepan en quien es lal princesita",
"como la sabndija q eres",
"amen brindo por ello",
"juega 5mil partidas mas",
"a ver si llegas al nivel de wmls",
"va tio copia mas rapido q me aburro",
"un retrasado lo coge antes q tu y tu eras el informatico",
"vaaa mamahuevos",
"copia mas rapido ramera",
"q nos aburrimos",
"yo informatico por petar partidas",
"puto murciano",
"tu eres subnormal",
"dale un platanito a tu madre ya de paso",
"todos los italianos hablan espanol menos frank ese cabron no.",
"me lo como yo el platanito protes buenas",
"pirate de mi puto barrio o te lleno de plomo, pavo",
"has visto mis fotos no",
"lol que, quieres dormir tu tb con los peces",
"entenderas q eso hay q alimentarlo para no quedarse como la mierda q ves en el espejo cada noche",
"para parecer que tiene un apple mierdoso",
"nos liamos a navajazos o que",
"no os confundais, no soy racista. el racismo es un crimen y el crimen es cosa de donyo",
"bueno ahi te quedas maja",
"a seguir con tus memeces pelele",
"esto son un cruzado y un infante que estan charlando antes de la batalla. tio, creo que mi mujer me pone los cuernos. por que piensas eso dice el infante.  me ha dicho, haber si te mueres de una vez, que hay 20 como tu esperando en la casa del padre",
"joder menudo analfabeto",
"ale agur adios princesita",
"esto es un campesino que esta explorando y se encuentra otro paseando lejos de su base. hey has encontrado minas. el otro campesino contesta sorprendido.  a mi no me mires yo estoy ordenando vacas.",
"esto es un sacerdote chino y un monje que estan meditando. oooooooooooooommmm, ooooooooooooommm. sin abrir los ojos el sacerdote dice. pequeno saltamontes, estas no te oigo un enano contesta. pequeno saltamontes tu padre. que el calvo de tu hijo hace una hora que se fue.",
"mas vale que te sientes y te pongas a leer a platon",
".a ver si nehhon me pone las mismas frases de soplapollas, que hoy me siento desatendido",
"a ti te sienta mal no dormir la siesta eh?",
"te lo has fumado ya? cuanta ansiedad",
"animador payaso de viejos",
"di mejor que tienes que pelartela en tu habitacion como un mono",
"permiteme que me ria de la idiosincracia de tu comportamiento metiendote con alguien que tiene vida",
"discutirlo en el campo de batalla",
"tengo un grado superior de tecnico y animador en actividades fisicodeportivas",
"yo afortunadamente no estoy entre barrotes",
"se nota por tus dejes de dramaturgo en tus relatos pero se lee entre lineas que tienes un don",
"muy bien me gusta q estes en semilibertad",
"como dramaturgo del siglo xxi deberias saberlo",
"cuanto se meten a las madres x medio es k la cosa se esta poniendo seria",
"a este tio no le tienen que pegar casi en clase",
"lo suyo es pegarse en tzar, en chat es de gays",
"si el muy mierdas no sabe ni jugar ni insultar",
"habra que contarte que los demas lo hacemos para que sepas que hay vida mas alla de las cuatro paredes de tu habitacion de friki",
"si me llamas mono hay mas tematicas que platanos y barrotes",
"te explico dramaturgo: aunque por aqui las frases carecen de entonacion, es evidente que se trata de ironias",
"deberias saber que esa profesional se gana mas de 5k euros al mes y mantiene una familia entera ",
"en este mundo para que las personas emprendedoras escalen debe haber muchos peones absurdos como tu a los que pasar por encima",
"si todo fueran emprendedores esto no seria espana, habria demasiada competencia y una conciencia colectiva mayor que nos ayudaria a conseguir nuestros objetivos como clase obrera",
"asi que hemos de conformarnos con tontos como tu, cuyas vidas carecen de sentido y/o rumbo, pero que sois felices desde vuestra ingenuidad",
"lo triste es que tu voto y tu persona sean valorados de manera equitativa a la de cualquier otro espanol con inquietudes, propositos y metas",
"voy a fumar que me sabe mal estar dandote tanta cana siendo tu un crio",
"si llegamos a estar en el tzar le mando alfombras con magos hasta que se rinda, aunque fuese mi aliado",
"jajajajaja encima s judio",
"cuando te saque un ojo con mi six pack a ver quien se rie",
"que te follen, te maten y luego violen tu cadaver",
"dios os castiga por hacer mapas",
"cuando ves a los frikis y repudiados del ano",
"cayate q te vas a quedar solo",
"quien coopera para regarlarle un libro a donyo para que amplie vocabulario?",
"oid, si en el tzar peto a raza, estoy cometiendo un genocidio?",
"donyo eres un comemierda y un abrazafarolas",
"vas a tener que leer mas y los letreros de salida de los bares no cuentan",
"pues yo te lo pongo facil, lee un libro, sin dibujitos ni nada, y quiza hable contigo",
"a partir de manana tye quiero ver con acento murciano, fumigando a tope y llenando de plomo a los pavos",
"uno de los pocos personajes que no es deforme, pero sigue siendo moro",
"yo soy el q viene aqui cuando no tiene nada q hacer debido a las condiciones de vida tan comodas de las que gozo",
"hasta en tu capacidad pauperrima de insultar vemos lo deficiente que eres",
"ese payaso q se cambia el nombre para parecer que tiene un apple mierdoso",
"and, nos liamos a navajazos o que?",
"no os confundais, no soy racista. el racismo es un crimen y el crimen es cosa de negros",
"he visto flanes de vainilla con mas huevos que tu",
"eres venezolano. se muy bien que en argentina existe una terrible discriminacion hacia la gente como tu. por eso no me sorprende tu comentario. demuestras un claro resentimiento hacia ellos. no te culpo, a mi me parece muy feo que alguien se burle de la gente de un pais por tener una complexion fisica caracteristica de los indios americanos o porque el pais sea de los mas subdesarrollados del continente.",
"de una puta y un gitano nacio el primer murciano",
"i am the king of kings, the god of godss, the king of the 7 kindoms, the protector of the rome, the capo di tutti li cappi, the cosa nostra boos, the head of the king. the god of the olimpo, the fuking king / god ares",
"eres un payaso q baila",
"viajo, veo sitios, me follo a diosas y gano mucho dinero",
"eso denota en tu personalidad un gran vacio",
"q a todos se os caen los huevos",
"si a la gente le haces perder el tiempo",
"estaba despistado y cuando pediste pausa, en lugar de dar pausa di suprimir y tenia tu granja seleccionada",
"ahora cuando tu hermana termine de chuparmela te respondo, no te preocupes",
"el estado de animo en el mismo procesador fisico, similar al ataque de los enemigos",
"donyo me han llamado del zoo dicen q vayas a hacer una actuacion quieren ver a un gorila bailar",
"se ha ido de tu partida y te ha dejado colgado como una puta mierda",
"lo recurdas saco de mierda? acabas de ponerte la cruz, vas a enterarte. te acordaras de lo miserable q eres. te lo hare recordar",
"hace dos dias comiendome la polla pidiendome consejos para mejorar comiendome los huevos como la sabndija q eres",
"mi mujer me hizo altavoz",
"te han sacado de la jaula ya?",
"juega 5mil partidas mas a ver si llegas al nivel. un retrasado lo coge antes q tu",
"josemi, no te lo desistales es una orden, asi que como deje de verte por aqui te parto el pecho. puto murciano",
"tu quieres que te parta el pecho o que puto murciano?",
"vienes? o has muerto por la calle ",
"pq no le damos una propina a la cacho puta de tu madre",
"aqui la unica que come platanos es tu puta madre",
"pirate de mi puto barrio o te lleno de plomo, pavo",
"lol que?, quieres dormir tu tb con los peces?",
"sigo infundiendo miedo..",
"qu pasa perro flauta, te doy 2 ostias y te undo",
"yo por mi nos liabamos a ostias pero rapido, pero no me gustaria ver a tu madre de luto",
"me pasais el hamachi ese",
"dais mas asco que el que siente spr alberto por davio y xekbo",
"pues es cierto, lo dais",
"jode que te maten y que se ponga a bailar encima de tu cadaver llamandote noob",
"esto es un campesino que esta explorando y se encuentra otro paseando lejos de su base. -hey has encontrado minas. el otro campesino contesta sorprendido. - a mi no me mires yo estoy ordenando vacas.",
"no me da tiempo de echar apenas una partida, pero si de leer el quijote referido a la 1.13b",
"i preffer bigger one",
"even ares has crawled back under his rock",
"i may have raped a hiv positive woman, but i will be fine because i took a shower afterwards.",
"i find this quite offensive, as my uncle died on 11-s. at least he died doing what he loved. flying planes.",
"1.11 is a graveyard where dinosaur donyo live. d-rex",
"eat shit nehhon",
"violaremos a vuestros caballos y huiremos en vuestras mujeres",
"nos comeremos a vuestros hijos mientras vuestras comidas miran",
"are you tired of being a rusian bastard?",
"lo hice el otro dia por hacer la gracia",
"yo tampoco te considero persona, te considero vaca",
"no just common sense? common mis cojones",
"ooohh my goddd such a big trouble, 2 wizzard, oohhh jesus crist",
"venga maricas, digo venga razaga",
"i will give one thousabd euros to anyone who joins",
"for once i am glad to see mamut hhhhhhhhhhh",
"pero no salgais puots payasos",
"ai k saber perder",
"kurwa",
"yo trato mejor a un perro que veo por la calle que a xekbo o davio",
"donovan, el hamachi es peligroso o te abre los poros o como se diga del pc? (porfavor di la verdad).",
"este juego es tan alucinante que cuando lo estaba viendo mi madre entro y penso que habia estado otra vez con las drogas, pero le dije que solo era un juego... lo malo es que mi madre murio hace 2 anos y yo ni siquiera tengo ordenador",
"osea que... sin vacilar ni deprimir aposta, no tienes ni madre ni ordenador y consigue jugar a tzar, y cuando jugabas tu madre te vio, osea, que quedamos que tu tienes un ordenador en la cabeza y tu madre es un fantasma, o esa es mi idea xdd.",
"sara joder consigue novio, fracasada fea",
"obeja obeja obeja obeja obeja obeja",
"yo prefiero no tener gente tan deleznable y ruin en mi clan cuando no lo necesito",
"te desearia que te vaya bien pero tus actos te condenan a que no sea asi ",
"como toda la basura que ha pasado por el clan hay que sacarla",
"arrieros somos y en el camino nos encontraremos. te vas a cagar, acuerdate",
"han pasado 20mil inutiles por aqui en muchos anos, y todos han acabado comiendome la polla. pero tu no te mereces ni eso, pq te daria placer con lo salida q vas",
"yo soy ares, el dios de los mares, el que reparte ostias a pares, el que destroza conos y putas por iguales, the king of kings, the fuking master, the god of goddes, the big ares",
"qu pasa perro silbato",
"no te hagas el sueco queremos ver tu preciosa tez",
"es espectacular q aun haya gnte aqui que siga tratando con el retrasado este",
"eres un comewevos q baila y eso no lo cambiara",
"eso nos da una buena constancia de tu vida social",
"estate quieto ahi ocultando tu imagen de despojo ",
"nos estamos cansando, despues de desconectarse de nuestra sala sin pactar nada con nosotros los azores y teniendo una sala que iba bien de ping, nos obligan ir a tres salas (2 de ellas que ni van) nosotros aceptamos aunque no le vemos sentido si iba bien la sala para jugar ahora en una sala peor de ping, luego decir despues de 15 minutos que quieren volver a la nuestra. y luego es defwin para ellos... claro...",
"los nuevos aun tienen dudas de si eres subnormal profundo o entrenas la habilidad de hacer tonto y el pena",
"la pagina es la mas moderna que aya visto nunca",
"que pagina tan grande no sabras donde se meten los mapas creados por mi",
"en la carpeta maps de tzar",
"por favor preguntad solo aqui dudas",
"quiero unirme al clan rey por favooooooooooooooooooorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
"para eso tienes que entrar en el tzar communicator al canal clan_rey",
"me puedes decir donde le pongo el nombre a un mapa?",
"en el editor de mapas en propiedades, perdona por el retraso",
"como puedo hacer en la mision puente cercano, para poder no ser amigo de los que tengo al lado. gracias! :)",
"buena pregunta, arriba donde estan los recursos a la derecha veras un pergamino y una mano cogiendo algo le das a la mano y te saldra postura diplomatica le das a las espadas y ya esta, espero que te sirva.",
"hola yo quisierasaber como se gira un punte por que no puedo cruzar el rio ayuda!!!",
"girar puertas y puentes control y alt",
"como puedo dar la vuelta a una puerta de la muralla?",
"como hago para q se vea la vida"]